services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: site-diary-mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "SiteDiary_Dev#2026"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
