services:
  mssql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: site-diary-mssql
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "SiteDiary_Dev#2026"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

  sitediary.web:
    build:
      context: .
      dockerfile: src/SiteDiary.Web/Dockerfile
    container_name: site-diary-web
    depends_on:
      - mssql
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
      ASPNETCORE_URLS: "http://+:8080"
    ports:
      - "5167:8080"
    volumes:
      # Map the host uploads folder into the container so the app can access /app/uploads
      - ./src/SiteDiary.Web/uploads:/app/uploads

volumes:
  mssql-data:
